services:
  prometheus-ring-api:
    build: .
    # environment:
    # -     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prometheus-ring
    ports:
      - "9988:9988"
    environment:
    - API_DOCKER_NETWORK=prometheus-ring
    - DOCKER_PROMETHEUS_IMAGE=prometheus-ring-node
    - API_ENDPOINT=prometheus-ring-api
    - API_PORT=9988
    - NODE_CAPACITY=4
    - NODE_MIN_LOAD=25
    - NODE_MAX_LOAD=75
    - NODE_SCRAPE_INTERVAL=5s
    - NODE_SD_REFRESH_INTERVAL=5s
    - LOG_LEVEL=WARNING
    - METRICS_DATABASE_URL=load-balancer
    - METRICS_DATABASE_PORT=9009
    - METRICS_DATABASE_PATH=/api/v1/push

networks:
  # prometheus-ring-api-network:
  #   external: true
  prometheus-ring:
    external: true
