services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - 3000:3000
    configs:
      - source: grafana_provisioning_datasources
        target: /etc/grafana/provisioning/datasources/datasource.yaml

  operator:
    image: augustodsgv/prometheus-ring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9988:9988"
    environment:
    - DOCKER_NETWORK=prometheus-ring_default
    
    - DOCKER_PROMETHEUS_IMAGE=augustodsgv/prometheus-ring-node
    - API_ENDPOINT=operator
    - API_PORT=9988
    - NODE_CAPACITY=500
    - NODE_REPLICATION_NUM=3
    - NODE_MIN_LOAD=25
    - NODE_MAX_LOAD=75
    - NODE_SCRAPE_INTERVAL=1m
    - NODE_SCRAPE_TIMEOUT=20s

    - SD_PROVIDER=consul
    - SD_PORT=8500
    - SD_HOST=consul

    - LOG_LEVEL=DEBUG
    - METRICS_DATABASE_URL=load-balancer
    - METRICS_DATABASE_PORT=9009
    - METRICS_DATABASE_PATH=/api/v1/push
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  load-balancer:
    image: nginx:latest
    ports:
      - "9009:9009"
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf

  mimir-1:
    image: augustodsgv/custom-mimir
    hostname: mimir-1
    volumes:
      - mimir-1-data:/data
    configs:
      - source: mimir_config
        target: /etc/mimir.yaml
      - source: mimir_alertmanager_fallback_config
        target: /etc/alertmanager-fallback-config.yaml

  mimir-2:
    image: augustodsgv/custom-mimir
    hostname: mimir-2
    volumes:
      - mimir-2-data:/data
    configs:
      - source: mimir_config
        target: /etc/mimir.yaml
      - source: mimir_alertmanager_fallback_config
        target: /etc/alertmanager-fallback-config.yaml

  mimir-3:
    image: augustodsgv/custom-mimir
    hostname: mimir-3
    volumes:
      - mimir-3-data:/data
    configs:
      - source: mimir_config
        target: /etc/mimir.yaml
      - source: mimir_alertmanager_fallback_config
        target: /etc/alertmanager-fallback-config.yaml

  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data

  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "limits": {
            "http_max_conns_per_client": 100000
          }
        }

volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:
  minio-data:

configs:
  mimir_config:
    file: ./mimir/mimir.yaml
  mimir_alertmanager_fallback_config:
    file: ./mimir/alertmanager.yaml
  grafana_provisioning_datasources:
    file: ./mimir/grafana-provisioning-datasources.yaml
  nginx:
    file: ./mimir/nginx.conf