# Building the go project
FROM golang:1.24-rc-alpine AS builder

WORKDIR /app

COPY mimir_utils .

RUN go build -o env_to_yaml

# Running
FROM alpine:3.12


# Copy the go binary - now from the correct path in the builder stage
COPY --from=builder /app/env_to_yaml /bin/env_to_yaml

WORKDIR /bin
# # Downloading the mimir binary
RUN apk update && apk add --no-cache curl 
RUN curl -fLo mimir https://github.com/grafana/mimir/releases/latest/download/mimir-linux-amd64
RUN chmod +x mimir

# # Copy the entry script -  Make sure the 'entry' file is in the same directory as your Dockerfile
COPY entry /entry

# EXPOSE 8080

ENTRYPOINT ["/entry"]