FROM alpine:3.12 AS stage
# Install necessary packages
RUN apk update && apk add --no-cache net-tools grep coreutils sed curl

WORKDIR /usr/local/bin
RUN curl -fLo mimir https://github.com/grafana/mimir/releases/latest/download/mimir-linux-amd64 -o mimir
RUN chmod +x mimir

COPY ./entrypoint.sh ./entrypoint.sh

CMD ["./entrypoint.sh"]