FROM prom/prometheus

EXPOSE 9090

ADD entry /

ENTRYPOINT  ["/entry"]
CMD         [   "--config.file=/etc/prometheus/prometheus.yml", \
                "--storage.tsdb.path=/prometheus", \
                "--web.console.libraries=/usr/share/prometheus/console_libraries", \
                "--web.console.templates=/usr/share/prometheus/consoles" ]