all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/augusto/.ssh/ed25519
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  children:
    managers:
      hosts:
        manager-0:
          ansible_host: 177.93.132.199
          private_ip: 172.30.0.8
        manager-1:
          ansible_host: 177.93.132.198
          private_ip: 172.30.0.58
        manager-2:
          ansible_host: 177.93.132.196
          private_ip: 172.30.0.78
    workers:
      hosts: {}
