#!/bin/sh
# Writing PROMETHEUS_YML environment var to the file
if [ -z "$PROMETHEUS_YML" ]; then
    echo "PROMETHEUS_YML environment variable is not set"
    exit 1
fi

echo $PROMETHEUS_YML | base64 -d > prometheus.yml
# /etc/prometheus/prometheus.yml

# exec /bin/prometheus "$@"