all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/augusto/.ssh/ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    managers:
      hosts:
        manager_0:
          ansible_host: x.x.x.x
          private_ip: x.x.x.x
        manager-1:
          ansible_host: x.x.x.x
          private_ip: x.x.x.x
    workers:
      hosts:
        worker_0:
          ansible_host: x.x.x.x
          private_ip: x.x.x.x
