all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/augusto/.ssh/ed25519
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  children:
    managers:
      hosts:
        manager-0:
          ansible_host: 177.93.132.189
          private_ip: 172.30.0.90
    workers:
      hosts:
        worker-0:
          ansible_host: 177.93.132.190
          private_ip: 172.30.0.75
        worker-1:
          ansible_host: 177.93.132.186
          private_ip: 172.30.0.114
        worker-2:
          ansible_host: 177.93.132.192
          private_ip: 172.30.0.93
